# Generated by Django 4.2 on 2025-04-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="название")),
            ],
            options={
                "verbose_name": "кампус",
                "verbose_name_plural": "кампусы",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studing_year",
                    models.IntegerField(
                        choices=[(4, 4), (1, 1), (3, 3), (2, 2)],
                        verbose_name="текущий год обучения",
                    ),
                ),
                ("letter", models.CharField(max_length=1, verbose_name="буква класса")),
                (
                    "year_created",
                    models.PositiveSmallIntegerField(
                        verbose_name="в каком календарном году был создан класс"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        verbose_name="используется ли класс в текущем учебном году",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campus",
                        verbose_name="кампус, которому принадлежит класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "класс",
                "verbose_name_plural": "классы",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "предмет",
                "verbose_name_plural": "предметы",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=20, verbose_name="фамилия")),
                ("name", models.CharField(max_length=20, verbose_name="имя")),
                (
                    "patronomic",
                    models.CharField(max_length=20, verbose_name="отчество"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="core.group",
                        verbose_name="класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "обучающийся",
                "verbose_name_plural": "обучающиеся",
            },
        ),
    ]
