# Generated by Django 4.2.20 on 2025-04-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "ученик", "verbose_name_plural": "ученики"},
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=30, verbose_name="название"),
        ),
    ]
