# Generated by Django 4.2.20 on 2025-05-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_student_options_alter_subject_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalMonthCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="начало отчётного периода"),
                ),
                ("end_date", models.DateField(verbose_name="конец отчётного периода")),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, verbose_name="является архивной записью"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_cards",
                        to="core.student",
                        verbose_name="ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Личная карточка",
                "verbose_name_plural": "Личные карточки",
            },
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
            ],
            options={
                "verbose_name": "Межпредметный навык",
                "verbose_name_plural": "Межпредметные навыки",
            },
        ),
        migrations.CreateModel(
            name="SoftSkillMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Нет", "Нет"),
                            ("Скорее нет", "Скорее нет"),
                            ("Скорее да", "Скорее да"),
                            ("Да", "Да"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="оценка",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_cards.personalmonthcard",
                        verbose_name="к какой карточке относится",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal_cards.softskill",
                        verbose_name="к какому навыку относится",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка межпредметного навыка",
                "verbose_name_plural": "Оценки межпредметных навыков",
            },
        ),
        migrations.CreateModel(
            name="PersonalStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="текст")),
                (
                    "personal_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strengths",
                        to="personal_cards.personalmonthcard",
                        verbose_name="к какой карточке относится",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="к какому предмету относится",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметка о проявленных успехах",
                "verbose_name_plural": "Проявленные успехи",
            },
        ),
        migrations.CreateModel(
            name="PersonalRecommendations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="текст")),
                (
                    "personal_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="personal_cards.personalmonthcard",
                        verbose_name="к какой карточке относится",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="к какому предмету относится",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персональная рекомендация",
                "verbose_name_plural": "Персональные рекомендации",
            },
        ),
    ]
