# Generated by Django 4.2.20 on 2025-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softskill",
            name="name",
            field=models.CharField(max_length=150, verbose_name="название"),
        ),
    ]
