# Generated by Django 4.2.20 on 2025-06-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personal_cards", "0002_alter_softskill_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalrecommendations",
            old_name="personal_card",
            new_name="card",
        ),
        migrations.RenameField(
            model_name="personalstrength",
            old_name="personal_card",
            new_name="card",
        ),
        migrations.AlterField(
            model_name="softskillmark",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="softskills_marks",
                to="personal_cards.personalmonthcard",
                verbose_name="к какой карточке относится",
            ),
        ),
    ]
