# Generated by Django 4.2.20 on 2025-06-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_student_options_alter_subject_name"),
        (
            "personal_cards",
            "0003_rename_personal_card_personalrecommendations_card_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonalMonthCard",
            new_name="PersonalCard",
        ),
    ]
