# Generated by Django 4.2.20 on 2025-06-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_student_options_alter_subject_name"),
        ("personal_cards", "0004_rename_personalmonthcard_personalcard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalcard",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="personalcard",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="personalcard",
            name="start_date",
        ),
        migrations.CreateModel(
            name="CardsBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="начало отчётного периода"),
                ),
                ("end_date", models.DateField(verbose_name="конец отчётного периода")),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, verbose_name="является архивированной"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.group",
                        verbose_name="к какой группе относится",
                    ),
                ),
            ],
            options={
                "verbose_name": "Папка с карточками",
                "verbose_name_plural": "Папки с карточками",
            },
        ),
    ]
