# Generated by Django 4.2.20 on 2025-06-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personal_cards", "0005_remove_personalcard_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalcard",
            name="batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="personal_cards.cardsbatch",
                verbose_name="к какой папке карточек относится",
            ),
            preserve_default=False,
        ),
    ]
