# Generated by Django 4.2 on 2025-06-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cards', '0006_personalcard_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcard',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='personal_cards.cardsbatch', verbose_name='к какой папке карточек относится'),
        ),
    ]
