# Generated by Django 4.2 on 2025-04-09 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tests_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                (
                    "studing_year",
                    models.IntegerField(
                        choices=[(4, 4), (1, 1), (3, 3), (2, 2)],
                        verbose_name="год обучения",
                    ),
                ),
                (
                    "last_update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="время последнего редактирования"
                    ),
                ),
            ],
            options={
                "verbose_name": "проверочная",
                "verbose_name_plural": "проверочные",
            },
        ),
        migrations.CreateModel(
            name="TestAssign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writing_date", models.DateField(verbose_name="дата написания")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests_app.group",
                        verbose_name="класс, которому назначен тест",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests_management.test",
                        verbose_name="тест",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="test",
            name="classes",
            field=models.ManyToManyField(
                through="tests_management.TestAssign",
                to="tests_app.group",
                verbose_name="классы, которые будут писать эту проверочную",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="составитель",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tests_management.subject",
                verbose_name="предмет",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num",
                    models.IntegerField(verbose_name="номер задания в проверочной"),
                ),
                (
                    "sub_num",
                    models.IntegerField(
                        null=True, verbose_name="подномер задания в проверочной"
                    ),
                ),
                (
                    "checked_skill",
                    models.CharField(max_length=300, verbose_name="проверяемый навык"),
                ),
                (
                    "max_points",
                    models.IntegerField(verbose_name="максимальное количество баллов"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tests_management.test",
                        verbose_name="к какому тесту относится",
                    ),
                ),
            ],
        ),
    ]
