# Generated by Django 4.2.20 on 2025-04-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tests_management",
            "0002_alter_task_options_alter_testassign_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="classes",
            new_name="groups",
        ),
        migrations.AlterField(
            model_name="test",
            name="studing_year",
            field=models.IntegerField(
                choices=[(4, 4), (1, 1), (3, 3), (2, 2)],
                verbose_name="для какого класса",
            ),
        ),
    ]
