# Generated by Django 4.2.20 on 2025-04-21 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_management', '0003_rename_classes_test_groups_alter_test_studing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='составитель'),
        ),
        migrations.AlterField(
            model_name='testassign',
            name='writing_date',
            field=models.DateField(null=True, verbose_name='дата написания'),
        ),
    ]
