# Generated by Django 4.2.20 on 2025-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tests_management",
            "0005_alter_task_sub_num_alter_task_test_alter_test_groups_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="sub_num",
        ),
        migrations.AddField(
            model_name="task",
            name="level",
            field=models.CharField(
                choices=[("Реф", "Рефлексивный"), ("Баз", "Базовый")],
                default="Реф",
                max_length=3,
                verbose_name="уровень",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="with_reflexive_level",
            field=models.BooleanField(
                default=False, verbose_name="есть ли рефлексивный уровень"
            ),
            preserve_default=False,
        ),
    ]
