# Generated by Django 4.2.20 on 2025-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0006_remove_task_sub_num_task_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.CharField(
                choices=[("Реф", "Рефлексивный"), ("Баз", "Базовый")],
                default="Баз",
                max_length=3,
                verbose_name="уровень",
            ),
        ),
    ]
