# Generated by Django 4.2.20 on 2025-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0007_alter_task_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="with_reflexive_level",
            field=models.BooleanField(
                default=False, verbose_name="есть ли рефлексивный уровень"
            ),
        ),
    ]
