# Generated by Django 4.2.20 on 2025-06-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0008_alter_test_with_reflexive_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="опубликован ли"),
        ),
        migrations.AlterField(
            model_name="testassign",
            name="writing_date",
            field=models.DateField(null=True, verbose_name="дата написания"),
        ),
    ]
