# Generated by Django 4.2.20 on 2025-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0008_alter_test_with_reflexive_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="опубликован ли"),
        ),
        migrations.AddField(
            model_name="test",
            name="month",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Сентябрь"),
                    (2, "Октябрь"),
                    (3, "Ноябрь"),
                    (4, "Декабрь"),
                    (5, "Январь"),
                    (6, "Февраль"),
                    (7, "Март"),
                    (8, "Апрель"),
                    (9, "Май"),
                    (10, "Июнь"),
                ],
                default=1,
                verbose_name="месяц написания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testassign",
            name="writing_date",
            field=models.DateField(null=True, verbose_name="дата написания"),
        ),
    ]
