# Generated by Django 4.2.20 on 2025-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0008_alter_test_with_reflexive_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="month",
            field=models.SmallIntegerField(
                choices=[
                    (9, "Сентябрь"),
                    (10, "Октябрь"),
                    (11, "Ноябрь"),
                    (12, "Декабрь"),
                    (1, "Январь"),
                    (2, "Февраль"),
                    (3, "Март"),
                    (4, "Апрель"),
                    (5, "Май"),
                    (6, "Июнь"),
                ],
                default=1,
                verbose_name="месяц написания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testassign",
            name="writing_date",
            field=models.DateField(null=True, verbose_name="дата написания"),
        ),
    ]
