# Generated by Django 4.2.20 on 2025-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0009_test_month_alter_testassign_writing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="month",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Сентябрь"),
                    (2, "Октябрь"),
                    (3, "Ноябрь"),
                    (4, "Декабрь"),
                    (5, "Январь"),
                    (6, "Февраль"),
                    (7, "Март"),
                    (8, "Апрель"),
                    (9, "Май"),
                    (10, "Июнь"),
                ],
                verbose_name="месяц написания",
            ),
        ),
    ]
