# Generated by Django 4.2.20 on 2025-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_student_options_alter_subject_name"),
        ("tests_management", "0009_test_is_published_test_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.CharField(
                choices=[("Баз", "Базовый"), ("Реф", "Рефлексивный")],
                default="Баз",
                max_length=3,
                verbose_name="уровень",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="tests",
                through="tests_management.TestAssign",
                to="core.group",
                verbose_name="классы, которые будут писать эту проверочную",
            ),
        ),
    ]
