# Generated by Django 4.2.20 on 2025-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0011_alter_task_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.CharField(
                choices=[("Баз", "Базовый"), ("Реф", "Рефлексивный")],
                default="Баз",
                max_length=3,
                verbose_name="уровень",
            ),
        ),
    ]
