# Generated by Django 4.2.20 on 2025-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_management", "0012_alter_task_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.CharField(
                choices=[("Реф", "Рефлексивный"), ("Баз", "Базовый")],
                default="Баз",
                max_length=3,
                verbose_name="уровень",
            ),
        ),
    ]
