# Generated by Django 4.2 on 2025-06-15 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_management', '0013_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('Баз', 'Базовый'), ('Реф', 'Рефлексивный')], default='Баз', max_length=3, verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное допустимое значение 1'), django.core.validators.MaxValueValidator(100, 'Максимально допустимое значение 100')], verbose_name='максимальное количество баллов'),
        ),
        migrations.AlterField(
            model_name='task',
            name='num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное допустимое значение 1')], verbose_name='номер задания в проверочной'),
        ),
    ]
