# Generated by Django 4.2 on 2025-04-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studing_year",
                    models.IntegerField(
                        choices=[(4, 4), (1, 1), (3, 3), (2, 2)],
                        verbose_name="текущий год обучения",
                    ),
                ),
                ("letter", models.CharField(max_length=1, verbose_name="буква класса")),
                (
                    "year_created",
                    models.PositiveSmallIntegerField(
                        verbose_name="в каком календарном году был создан класс"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        verbose_name="используется ли класс в текущем учебном году",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=20, verbose_name="фамилия")),
                ("name", models.CharField(max_length=20, verbose_name="имя")),
                (
                    "patronomic",
                    models.CharField(max_length=20, verbose_name="отчество"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.SmallIntegerField(verbose_name="результат в баллах")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_solutions",
                        to="tests_app.student",
                        verbose_name="ученик",
                    ),
                ),
            ],
        ),
    ]
