# Generated by Django 4.2 on 2025-04-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tests_management", "0001_initial"),
        ("tests_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksolution",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="tests_management.task",
                verbose_name="задание",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="tests_app.group",
                verbose_name="класс",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="tasks",
            field=models.ManyToManyField(
                through="tests_app.TaskSolution",
                to="tests_management.task",
                verbose_name="решенные задания",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="tests",
            field=models.ManyToManyField(
                related_name="students",
                to="tests_management.test",
                verbose_name="решенные проверочные",
            ),
        ),
    ]
