# Generated by Django 4.2 on 2025-04-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        (
            "tests_management",
            "0002_alter_task_options_alter_testassign_options_and_more",
        ),
        ("tests_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="group",
        ),
        migrations.RemoveField(
            model_name="student",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="student",
            name="tests",
        ),
        migrations.AlterModelOptions(
            name="tasksolution",
            options={"verbose_name": "решение", "verbose_name_plural": "решения"},
        ),
        migrations.AlterField(
            model_name="tasksolution",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_solutions",
                to="core.student",
                verbose_name="ученик",
            ),
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
